# Generated by Django 5.1.5 on 2025-01-18 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_categoryofdish_dish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booktabel',
            name='phone_number',
            field=models.CharField(max_length=16),
        ),
    ]
